#!/bin/sh

set -e
. ../../../nvme.sh

NVME_TEST_VERSION=v0.10.7

# Remove the stuff we're clobbering.
[ -e ../../../$NVME_TEST_VERSION ] && rm -R ../../../$NVME_TEST_VERSION

# Install from source
nvme install -s $NVME_TEST_VERSION

# Check
[ -d ../../../$NVME_TEST_VERSION ]
nvme run $NVME_TEST_VERSION --version | grep $NVME_TEST_VERSION
