#!/bin/sh

set -e
. ../../nvme.sh

# Remove the stuff we're clobbering.
[ -e ../../v0.10.25 ] && rm -R ../../v0.10.25
[ -e ../../v0.10.26 ] && rm -R ../../v0.10.26

# Install from binary
nvme install 0.10.25
nvme install 0.10.26

# Check
[ -d ../../v0.10.25 ]
[ -d ../../v0.10.26 ]

# Use the first one
nvme use 0.10.25

# Use the latest one
nvme use 0.10
node --version | grep v0.10.26
